name: Nightly

on:
  schedule:
    - cron: "0 5 * * *" # daily at 05:00
  workflow_dispatch:

env:
  RELEASE_COMMIT_MESSAGE: "chore(release): publish"
  RUN_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  visual-tests:
    name: Visual Tests
    uses: ./.github/workflows/tests-visual.yml
    secrets: inherit

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-all: true

  notify-fail:
    name: Notify Fail
    needs: [tests, build, visual-tests]
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Notify Failure
        uses: slackapi/slack-github-action@v3.0.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: "ui-kit-internal"
            attachments:
              - mrkdwn_in:
                  - text
                color: "#C62828"
                title: "${{ github.workflow }} finished: failure"
                title_link: "${{ env.RUN_URL }}"
